### ISSUE TITLE
Extra properties of Interface Message

### ISSUE THREAD

**Issue by shinytang6** [samdenty99/console-feed#1]
Hey, thanks for your great work done here! 
l wanna ask can you enable optional properties in interface `Message` ?

**Comment by samdenty99** [comment]
What would you mean by optional? ie. Leaving out some existing properties, adding a custom property handler, or changing the typings?

**Comment by shinytang6** [comment]
l mean adding a custom property handler, l need to dynamically assign some properties except `data`, `id`, `method`

**Comment by shinytang6** [comment]
Adding something like `[prop: string]: any` may help, do you think it's okay?

**Comment by samdenty99** [comment]
Could you provide a snippet that would utilize this custom property handler? can't really understand what you're trying to do right now

**Comment by shinytang6** [comment]
```
render() {
    return (
      <div style={{ backgroundColor: '#242424' }}>
        <Console
          logs={
            [{
              'method':"log",
              "data": [Array(1,2,3)],
              "id": "1",
              "other":"xxx"   // don't support that
            }]
          }
          variant="light"
        />
      </div>
    )
  }
```
