### ISSUE TITLE
It doesn't print correct output for Map

### ISSUE THREAD

**Issue by abdullahtariq1171** [samdenty99/console-feed#7]
```
let myMap = new Map();
myMap.set({}, "value associated with obj")

console.log(myMap)
```

Output:
<img width="1424" alt="screen shot 2018-10-13 at 7 15 33 pm" src="https://user-images.githubusercontent.com/5623766/46906410-72fcbc80-cf1c-11e8-833a-0ee92e8c1eb4.png">
***
I believe this is not the expected behavior. It doen't output key/value of map.

**Comment by samdenty99** [comment]
Map objects would need a new transformer that iterates over the maps entries + converts to plain object.

https://github.com/samdenty99/console-feed/blob/master/src/Transform/Function.ts is an example of how to implement one
